language: node_js
node_js:
  - 10
  - 9
  - 8
cache:
  directories:
    - node_modules
before_script:
  - npm install -g polymer-cli
  - rm -f /home/travis/build/climba03003/BiliLive-Recorder-Web-Client/index.html
  - mv /home/travis/build/climba03003/BiliLive-Recorder-Web-Client/index.travis.html /home/travis/build/climba03003/BiliLive-Recorder-Web-Client/index.html
script:
  - polymer build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build/es6-unbundled
  on:
    branch: master
