language: node_js
node_js:
  - 10
  - 9
  - 8
cache:
  directories:
    - node_modules
before_script:
  - npm install -g polymer-cli
script:
  - polymer build
deploy:
  provider: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build/es6-unbundle
  on:
    branch: master
